pipeline:
  build:
    image: plugins/docker
    group: build
    repo: no0dles/angular-docker-registry
    dry_run: true
    when:
      event:
        exclude: [ tag ]

  publish:
    image: plugins/docker
    repo: no0dles/angular-docker-registry
    tags: ["latest", "${DRONE_TAG}"]
    secrets: [ docker_username, docker_password ]
    when:
      event: tag
